crypto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import views as home_views

urlpatterns = [
    path("", home_views.home_page, name="Home_page"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('profiles/', include('profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('registeration/', views.registeration, name="Registeration"),
    path('login/', auth_views.LoginView.as_view(template_name="pages/users/login.html"), name="Login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="pages/users/logout.html"), name="Logout"),
]

profiles/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User


# User Profiles Model
class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='profile_images/', default="profile_images/default.png")
    api_key = models.CharField(max_length= 255)
    api_security_key = models.CharField(max_length= 255)


    def __str__(self):
        return self.user.username


# Market Coins
class MarketCoins(models.Model):
    coin_name = models.CharField(max_length= 100)
    coin_symbol = models.CharField(max_length= 10)
    coin_image = models.ImageField(upload_to='coin_images/', default="coin_images/default.png")
    trading_factor = models.CharField(max_length= 10, default="0.01")
    
    def __str__(self):
        return str(self.coin_name)


# Trading Type
class TradingType(models.Model):
    trading_name = models.CharField(max_length= 100)
    trading_symbol = models.CharField(max_length= 50)
    
    def __str__(self):
        return str(self.trading_name)


# Trading Status
class TradingStatus(models.Model):
    trading_status_name = models.CharField(max_length= 100)
    trading_status_symbol = models.CharField(max_length= 50)
    
    def __str__(self):
        return str(self.trading_status_name)

# Trading Status
class TradingOrderType(models.Model):
    trading_order_type_name = models.CharField(max_length= 100)
    trading_order_type_symbol = models.CharField(max_length= 50)
    
    def __str__(self):
        return str(self.trading_order_type_name)

# Profile Diret Orders
class ProfileDirectOrder(models.Model):
    profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    first_trading_coin = models.ForeignKey(MarketCoins, on_delete=models.CASCADE, related_name='first_trading_coin')
    second_trading_coin = models.ForeignKey(MarketCoins, on_delete=models.CASCADE, related_name='second_trading_coin')
    order_quantity = models.CharField(max_length= 100)
    limit_order_quantity = models.CharField(max_length= 100, default="0.0")
    trading_type = models.ForeignKey(TradingType, on_delete=models.CASCADE) 
    trading_order_type = models.ForeignKey(TradingOrderType, on_delete=models.CASCADE)
    trading_status = models.ForeignKey(TradingStatus, on_delete=models.CASCADE) 
    
    def __str__(self):
        return f"[{str(self.profile.user.username)}]-[{str(self.first_trading_coin.coin_symbol)}/{str(self.second_trading_coin.coin_symbol)}]" 

# Progile Automatic Tradings
class ProfileTrading(models.Model):
    profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    first_trading_coin = models.ForeignKey(MarketCoins, on_delete=models.CASCADE, related_name='first_profile_trading_coin')
    second_trading_coin = models.ForeignKey(MarketCoins, on_delete=models.CASCADE, related_name='second_profile_trading_coin')
    trading_quantity = models.CharField(max_length= 100)
    target_quantity = models.CharField(max_length= 100)
    trading_type = models.ForeignKey(TradingType, on_delete=models.CASCADE) 
    trading_status = models.CharField(max_length= 2, choices = (('0', 'RUN'),('1', 'COMPLETE'),('3', 'STOP'),), default=0)
    
    def __str__(self):
        return f"[{str(self.profile.user.username)}]-[{str(self.first_trading_coin.coin_symbol)}/{str(self.second_trading_coin.coin_symbol)}]" 

# Progile Automatic Tradings
class ProfileTradingOrders(models.Model):
    trading = models.ForeignKey(ProfileTrading, on_delete=models.CASCADE)
    first_trading_coin_quantity = models.CharField(max_length= 100)
    second_trading_coin_quantity = models.CharField(max_length= 100)
    trading_order_type = models.ForeignKey(TradingOrderType, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"[{str(self.trading.profile.user.username)}]-[{str(self.trading.first_trading_coin.coin_symbol)}/{str(self.trading.second_trading_coin.coin_symbol)}][{str(self.first_trading_coin_quantity)}/{str(self.second_trading_coin_quantity)}]" 


# Profile Automatic Trading Current trading coins market value
class AutomaticTradingCOinsMarketValues(models.Model):
    trading = models.ForeignKey(ProfileTrading, on_delete=models.CASCADE)
    first_coin_market_value = models.CharField(max_length= 100)
    second_coin_market_value = models.CharField(max_length= 100)
    market_open = models.CharField(max_length= 255, default= "0")
    market_close = models.CharField(max_length= 255, default= "0")
    market_high = models.CharField(max_length= 255, default= "0")
    market_low = models.CharField(max_length= 255, default= "0")

    def __str__(self) -> str:
        return f"[{self.trading.first_trading_coin.coin_symbol}/ {self.trading.second_trading_coin.coin_symbol}][{self.first_coin_market_value}/{self.second_coin_market_value}]"



users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisteration(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["first_name", "last_name","username", "email", "password1", "password2"]
    

    def __init__(self, *args, **kwargs):
        super(UserRegisteration, self).__init__(*args, **kwargs)

        # Username Field
        self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        self.fields['first_name'].widget.attrs['required'] = 'true'

        # Username Field
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        self.fields['last_name'].widget.attrs['required'] = 'true'

        # Username Field
        self.fields['username'].widget.attrs['placeholder'] = 'Username'

        # Email Field
        self.fields['email'].widget.attrs['placeholder'] = 'Email'

        # Password Field
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'

        # confirm password Field
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm password'

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import UserRegisteration

# Create your views here.
def registeration(request):
    if request.method == 'POST':
        form = UserRegisteration(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"thank you {username} Account Created Successfully")
            return redirect('Login')
    else:
        form = UserRegisteration()
    return render(request, "pages/users/registeration.html" , {"form": form})

templates/pages/users/create_profile_first_time.html
{% extends 'pages/users/login_and_registeration_base.html' %} {% load static %}

<!-- Page Title -->
{% block title %}Create Account | Elsherbiniy Crypto{% endblock title %}


<!-- Current Page Styles Files -->
{% block StylesFiles %}

<style>
  #id_profile_image{
    position: relative;
  }

  ::-webkit-file-upload-button {
    background-color: #2196f3;
    color: #fff;
    border-width: 0;
    border-radius: 5px;
    padding: 5px 10px;
    position: absolute;
    left: 0;
    top: 0;
    height: 100%;
    width: 100%;
  }

  .profile-image-span{
    display: block !important;
    font-size: 16px !important;
    background-color: transparent !important;
  }

</style>

{% endblock StylesFiles %}


<!-- Body Content-->
{% block body %} {% csrf_token %}
<!-- Start of Formly [ 1 ] Basic  -->
<section class="Formly Formly-Flat">
  <div class="Formly-Flat-Form-Container">
    <!-- Start Of Formly Head [ Logo ] -->
    <div class="Formly-Header">
      <div class="Formly-Header-logo">
        <!-- Create Logo Using Img [ png , jpg , svg] Remove Comment To Use This Option-->

        <div class="img-log">
          <img
            src="{% static 'base/images/logo.png' %}"
            alt="logo"
            title="Formy"
          />
        </div>
      </div>
      <!-- Logo Name-->
    </div>
    <!-- End Of Formly Head [ Logo ] -->
    <div class="Formly-Flat-Forms Formly-Flat-Register-Form">
      <!-- Start Of Form Header -->
      <div class="Formly-Flat-Form-Header">
        <div class="Formly-Flat-Form-Title">
          <h3>Create Profile</h3>
        </div>
        <div class="Formly-Flat-Form-sub-title">
          <span>Complete your profile and start trading</span>
        </div>
      </div>
      <!-- End Of Form Header -->
      <!-- Start Of Form -->
      <form method="POST" action="{% url 'create_profile' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div>{{form}}</div>

        <div class="col-12">
          <div class="Formly-Submit">
            <button type="submit" class="Formly-btn">Create Profile</button>
          </div>
        </div>
      </form>
      <!-- End Of Form -->
      <!-- Start Of Form Footer -->
      <div class="row">
        <div class="col-12 Formly-Flat-swap-Link">
          <span><a class="login" href="{% url 'Home_page' %}">Home</a></span>
          <span>- OR -</span>
          <span><a class="login" href="{% url 'Logout' %}">Logout</a></span>
        </div>
      </div>
      <!-- End Of Form Footer -->
    </div>
  </div>
</section>
<!-- End Of Formly [ 1 ] Basic  -->

{% endblock body %}

<!-- Current Page Scripts Files -->
{% block ScriptsFiles %} 

<script>

  $(document).ready(function () {
    
    // Create Label For Image field
    $("#id_profile_image").parent().prepend("<span class='profile-image-span'>Profile Image</span>")

  });

</script>

{% endblock ScriptsFiles %}

templates/pages/users/login.html
{% extends 'pages/users/login_and_registeration_base.html' %} {% load static %}

<!-- Page Title -->
{% block title %}Create Account | Elsherbiniy Crypto{% endblock title %}

<!-- Body Content-->
{% block body %}
{% csrf_token %}
<!-- Start of Formly [ 1 ] Basic  -->
<section class="Formly Formly-Flat">
  <div class="Formly-Flat-Form-Container">
    <!-- Start Of Formly Head [ Logo ] -->
    <div class="Formly-Header">
      <div class="Formly-Header-logo">
        <!-- Create Logo Using Img [ png , jpg , svg] Remove Comment To Use This Option-->

        <div class="img-log">
          <img
            src="{% static 'base/images/logo.png' %}"
            alt="logo"
            title="Formy"
          />
        </div>
      </div>
      <!-- Logo Name-->
    </div>
    <!-- End Of Formly Head [ Logo ] -->
    <div class="Formly-Flat-Forms Formly-Flat-Register-Form">
      <!-- Start Of Form Header -->
      <div class="Formly-Flat-Form-Header">
        <div class="Formly-Flat-Form-Title">
          <h3>Login into account</h3>
        </div>
        <div class="Formly-Flat-Form-sub-title">
          <span>Use your credenitials to access your account</span>
        </div>
      </div>
      <!-- End Of Form Header -->
      <!-- Start Of Form -->
      <form method="POST">
        {% csrf_token %}
        <div>{{form}}</div>

        <div class="col-12">
          <div class="Formly-Submit">
            <button type="submit" class="Formly-btn">Login</button>
          </div>
          <div class="Formly-Forget-Password">
            <span>Forget Password ?</span>
          </div>
        </div>
      </form>
      <!-- End Of Form -->
      <!-- Start Of Form Footer -->
      <div class="row">
        <div class="col-12 Formly-Flat-swap-Link">
          <span
            >Don't have an account?
            <a class="Register" href="{% url 'Registeration' %}"
              >Register Here</a
            ></span
          >
        </div>
      </div>
      <!-- End Of Form Footer -->
    </div>
  </div>
</section>
<!-- End Of Formly [ 1 ] Basic  -->

{% endblock body %}

<!-- Current Page Scripts Files -->
{% block ScriptsFiles %}
<script type="text/javascript">
  $(document).ready(function () {
    // Add Username placeholder
    document
      .querySelector("#id_username")
      .setAttribute("placeholder", "Username");

    // Add Password placeholder
    document
      .querySelector("#id_password")
      .setAttribute("placeholder", "Password");
  });
</script>
{% endblock ScriptsFiles %}

templates/pages/users/login_and_registeration_base.html
{% load static %}

<!-- Start HTML Code -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Main Meta Tags -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Important Meta Tags -->
    <meta name="author" content="elsherbiniy.me" />
    <meta
      name="description"
      content="Welcome To Elsherbiniy Crypto"
    />
    <meta name="keywords" content="Crypto, trading, bitcoin" />

    <!-- Library Styles -->
    <link
      rel="stylesheet"
      href="{% static 'base/css/libs/bootstrap.min.css' %}"
    />

    <!-- Main Style -->
    <link rel="stylesheet" href="{% static 'base/css/libs/forms.css' %}" />

    <!-- Current Page Styles Files -->
    {% block StylesFiles %} {% endblock StylesFiles %}

    <!-- Page Title & Icon -->
    <title>{% block title %} {% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'base/images/logo.png' %}" />
  </head>
  <body>
    <!--[if lt IE 7]>
      <p class="browsehappy">
        You are using an <strong>outdated</strong> browser. Please
        <a href="#">upgrade your browser</a> to improve your experience.
      </p>
    <![endif]-->

    <!-- Body Content -->
    {% block body %} {% endblock body %}

    <!-- External Libraries Scripts -->
    <script src="{% static 'base/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/popper.js' %}"></script>

  
    <script type="text/javascript">
      $(document).ready(function () {
        // Remove form Lables
        var labels = document.querySelectorAll("label");
        labels.forEach((e) => e.remove());

        // remove help text
        var helpText = document.querySelectorAll(".helptext");
        helpText.forEach((e) => e.remove());

        // remove the brs
        var brs = document.querySelectorAll("br");
        brs.forEach((e) => e.remove());
      });

    </script>

    <!-- Current Page Scripts Files -->
    {% block ScriptsFiles %} {% endblock ScriptsFiles %}

  </body>
</html>

templates/pages/users/logout.html
{% extends 'pages/users/login_and_registeration_base.html' %} {% load static %}

<!-- Page Title -->
{% block title %}Create Account | Elsherbiniy Crypto{% endblock title %}

<!-- Body Content-->
{% block body %}

<!-- Start of Formly [ 1 ] Basic  -->
<section class="Formly Formly-Flat">
  <div class="Formly-Flat-Form-Container">
    <!-- Start Of Formly Head [ Logo ] -->
    <div class="Formly-Header">
      <div class="Formly-Header-logo">
        <!-- Create Logo Using Img [ png , jpg , svg] Remove Comment To Use This Option-->

        <div class="img-log">
          <img
            src="{% static 'base/images/logo.png' %}"
            alt="logo"
            title="Formy"
          />
        </div>
      </div>
      <!-- Logo Name-->
    </div>
    <!-- End Of Formly Head [ Logo ] -->
    <div class="Formly-Flat-Forms Formly-Flat-Register-Form">
      <!-- Start Of Form Header -->
      <div class="Formly-Flat-Form-Header">
        <div class="Formly-Flat-Form-Title">
          <h3>You are logged out</h3>
        </div>
        <div class="Formly-Flat-Form-sub-title">
          <span>Use your credenitials to access your account</span>
        </div>
      </div>
      <!-- End Of Form Header -->
      <!-- Start Of Form Footer -->
      <div class="row">
        <!-- Redirection Links -->
        <div class="col-12 Formly-Flat-swap-Link">
          <span class="redirect-links"
            ><a class="Register" href="{% url 'Home_page' %}">Home</a></span
          >
          <span class="redirect-links"
            ><a class="Register" href="{% url 'Login' %}">Login</a></span
          >
          <span class="redirect-links"
            ><a class="Register" href="{% url 'Registeration' %}"
              >Create Account</a
            ></span
          >
        </div>
      </div>
      <!-- End Of Form Footer -->
    </div>
  </div>
</section>
<!-- End Of Formly [ 1 ] Basic  -->

{% endblock body %}

templates/pages/users/registeration.html
{% extends 'pages/users/login_and_registeration_base.html' %} {% load static %}

<!-- Page Title -->
{% block title %}Create Account | Elcaptain Group{% endblock title %}

<!-- Body Content-->
{% block body %} {% csrf_token %}
<!-- Start of Formly [ 1 ] Basic  -->
<section class="Formly Formly-Flat">
  <div class="Formly-Flat-Form-Container">
    <!-- Start Of Formly Head [ Logo ] -->
    <div class="Formly-Header">
      <div class="Formly-Header-logo">
        <!-- Create Logo Using Img [ png , jpg , svg] Remove Comment To Use This Option-->

        <div class="img-log">
          <img
            src="{% static 'base/images/logo.png' %}"
            alt="logo"
            title="Formy"
          />
        </div>
      </div>
      <!-- Logo Name-->
    </div>
    <!-- End Of Formly Head [ Logo ] -->
    <div class="Formly-Flat-Forms Formly-Flat-Register-Form">
      <!-- Start Of Form Header -->
      <div class="Formly-Flat-Form-Header">
        <div class="Formly-Flat-Form-Title">
          <h3>Create an account</h3>
        </div>
        <div class="Formly-Flat-Form-sub-title">
          <span>Setup a new account in a minute</span>
        </div>
      </div>
      <!-- End Of Form Header -->
      <!-- Start Of Form -->
      <form method="POST">
        {% csrf_token %}
        <div>{{form}}</div>

        <div class="col-12">
          <div class="Formly-Submit">
            <button type="submit" class="Formly-btn">Register</button>
          </div>
        </div>
      </form>
      <!-- End Of Form -->
      <!-- Start Of Form Footer -->
      <div class="row">
        <div class="col-12 Formly-Flat-swap-Link">
          <span
            >Already have an account?
            <a class="login" href="{% url 'Login' %}">Login Here</a></span
          >
        </div>
      </div>
      <!-- End Of Form Footer -->
    </div>
  </div>
</section>
<!-- End Of Formly [ 1 ] Basic  -->

{% endblock body %}